#pragma once
#include <string>
#include "canvas.h"

struct ppm_t
{
	// MEMBER VARIABLES
	std::string data{};

	// CONSTRUCTOR
	/**
	 * @brief Constructs a `ppm_t` object from a given canvas and optional maximum
	 *        line length for the PPM file output.
	 *
	 * This constructor generates a PPM (Portable PixMap) representation of the canvas,
	 * which includes pixel data and the PPM header. The canvas is converted to a PPM
	 * format, and the resulting pixel data is formatted to ensure that each line in the
	 * output does not exceed the specified maximum number of characters.
	 *
	 * If `max_chars` is not provided, the default value of `70` characters per line
	 * is used. The PPM format will attempt to keep each line within this length for
	 * better readability and to avoid excessively long lines.
	 *
	 * @param canvas The `canvas_t` object representing the canvas to be converted
	 *               into PPM format. This object contains the pixel data that will
	 *               be used to create the PPM output.
	 * @param max_chars (Optional) The maximum number of characters allowed per line
	 *                   in the PPM file. The default is 70. This value controls the
	 *                   width of each line in the pixel data section of the PPM file.
	 *
	 * @note The PPM format generated by this constructor will be a plain text format
	 *       that includes both the header (which specifies the image format and dimensions)
	 *       and the pixel data.
	 */
	ppm_t(const canvas_t& canvas, int max_chars = 70);
};